import { IProject } from "../types";

export const projects: IProject[] = [
  {
    _id: "1",
    title: "SPet",
    createdAt: new Date(),
    description:
      "Aplicación web que permite ayudar a encontrar a las mascotas perdidas de los usuarios por medio de indicaciones, comentarios, chat en tiempo real, fotos, gps.",
    image: "assets/img/projects/01.jpg",
    tags: [
      "React",
      "Mui",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Socketio",
      "Cloudinary",
      "Jwt",
      "NodeMailer",
      "Leaflet",
      "Framer motion",
      "Axios",
      "Formik",
      "Joi",
      "Yup",
      "Dark Mode",
      "Light Mode",
    ],
    source: "https://github.com/jerson100/searchPet-frontend",
    linkApp: "https://search-pet.netlify.app/pets/lost",
  },
  {
    _id: "2",
    title: "Foxbel Music",
    createdAt: new Date(),
    description:
      "Reproductor web de música con la posibilidad de buscar canciones, haciendo uso de la api de deezer",
    image: "assets/img/projects/02.jpg",
    tags: [
      "React",
      "Styled components",
      "Framer motion",
      "Typescript",
      "Context Api",
    ],
    source: "https://github.com/jerson100/Prueba-tecnica-frontend-fractalUp",
    linkApp: "https://music-foxbel.netlify.app/canciones",
  },
  {
    _id: "3",
    title: "Real time Bookmarks",
    createdAt: new Date(),
    description: "Arrastrar el marcador en el mapa en tiempo real",
    image: "assets/img/projects/03.jpg",
    tags: [
      "React",
      "Typescript",
      "NodeJs",
      "ExpressJs",
      "Socketio",
      "Leaflet",
      "Styled components",
    ],
    source: "https://github.com/jerson100/realtime-bookmarks-frontend",
    linkApp: "https://realtime-bookmarks.netlify.app/",
  },
  {
    _id: "4",
    title: "Tic tac toe",
    createdAt: new Date(),
    description: "Juego de Tic tac toe",
    image: "assets/img/projects/04.jpg",
    tags: ["React", "Typescript", "Styled components"],
    source: "https://github.com/jerson100/tic-tac-toe",
    linkApp: "https://tictatoe-react.netlify.app/",
  },
  {
    _id: "5",
    title: "Menú Lateral",
    createdAt: new Date(),
    description: "Menú lateral responsive",
    image: "assets/img/projects/05.jpg",
    tags: ["Html5", "Css3", "Responsive Web Design", "Bem"],
    source: "https://github.com/jerson100/menu-lateral",
    linkApp: "https://lateralmenu.netlify.app/",
  },
  {
    _id: "6",
    title: "Rest countries api",
    createdAt: new Date(),
    description:
      "Ejercicio de frontend mentor consumiento la api de restcountries",
    image: "assets/img/projects/06.jpg",
    tags: [
      "React",
      "Api",
      "Javascript",
      "Responsive Web Design",
      "Dark Mode",
      "Light Mode",
      "Styled components",
    ],
    source: "https://github.com/jerson100/Rest-countries-api",
    linkApp: "https://countries-apirest.netlify.app/",
  },
  {
    _id: "7",
    title: "Todo List",
    createdAt: new Date(),
    description: "Agregar, eliminar, editar y listar tareas",
    image: "assets/img/projects/07.jpg",
    tags: [
      "React",
      "Api",
      "Javascript",
      "Responsive Web Design",
      "Styled components",
      "NodeJs",
      "ExpressJs",
      "MongoDB",
      "Mern",
    ],
    source: "https://github.com/jerson100/Task-Easy-Fronted",
    linkApp: "https://jerson-easy-tasks.netlify.app/",
  },
  {
    _id: "8",
    title: "Gasto Semanal",
    createdAt: new Date(),
    description: "Aplicación para ver el gasto semanal",
    image: "assets/img/projects/08.jpg",
    tags: ["React", "sass", "Responsive Web Design"],
    source: "https://github.com/jerson100/gastoSemanalReatcJs",
    linkApp: "https://jerson100.github.io/gastoSemanalReatcJs/",
  },
  {
    _id: "9",
    title: "Diseño chat unjfsc",
    createdAt: new Date(),
    description:
      "Diseño de un chat web para el curso de criptografía de la UNJFSC",
    image: "assets/img/projects/09.jpg",
    tags: ["Html5", "Css3", "Responsive Web Design", "Bem"],
    source: "https://github.com/jerson100/chat_with_css_html_js",
    linkApp: "https://jerson100.github.io/chat_with_css_html_js/",
  },
  {
    _id: "10",
    title: "Fylo dark theme landing page",
    createdAt: new Date(),
    description: "Challenge frontend mentor sobre una landing page",
    image: "assets/img/projects/10.jpg",
    tags: [
      "Html5",
      "Css3",
      "Responsive Web Design",
      "Bem",
      "Variables css",
      "Frontend Mentor",
    ],
    source: "https://github.com/jerson100/chat_with_css_html_js",
    linkApp: "https://jerson100.github.io/chat_with_css_html_js/",
  },
  {
    _id: "11",
    title: "Acortador de url - Shortly",
    createdAt: new Date(),
    description:
      "Challenge frontend mentor sobre shortly, acortador de url que usa de la api rel.ink",
    image: "assets/img/projects/11.jpg",
    tags: [
      "Html5",
      "Css3",
      "Javascript",
      "Responsive Web Design",
      "Bem",
      "Variables css",
      "Frontend Mentor",
      "Api",
    ],
    source: "https://github.com/jerson100/ShortlyUrl",
    linkApp: "https://jerson100.github.io/ShortlyUrl/",
  },
  {
    _id: "12",
    title: "GiftExpertApp",
    createdAt: new Date(),
    description: "Filtro de gifs, usando la api de giphy",
    image: "assets/img/projects/12.jpg",
    tags: [
      "Html5",
      "Css3",
      "Javascript",
      "Responsive Web Design",
      "Bem",
      "Variables css",
      "Api",
    ],
    source: "https://github.com/jerson100/react-firstApp",
    linkApp: "https://jerson100.github.io/react-firstApp/",
  },
  {
    _id: "13",
    title: "RandomImage",
    createdAt: new Date(),
    description: "Generar y mostrar imágenes en posiciones aleatorias",
    image: "assets/img/projects/13.jpg",
    tags: ["Html5", "Css3", "Javascript"],
    source: "https://github.com/jerson100/show-random-images.github.io",
    linkApp: "https://jerson100.github.io/show-random-images.github.io/",
  },
  {
    _id: "14",
    title: "Bookmark landing page",
    createdAt: new Date(),
    description: "Challenge frontend mentor sobre una landing page - Bookmark",
    image: "assets/img/projects/14.jpg",
    tags: ["Html5", "Css3", "Javascript"],
    source: "https://github.com/jerson100/bookmark-landing-page-master",
    linkApp: "https://jerson100.github.io/bookmark-landing-page-master/",
  },
  {
    _id: "15",
    title: "LibreApp",
    createdAt: new Date(),
    description: "Diseño de página de libros básico",
    image: "assets/img/projects/15.jpg",
    tags: ["Html5", "Css3", "Bem"],
    source: "https://github.com/jerson100/meet_localstorage",
    linkApp: "https://jerson100.github.io/meet_localstorage/",
  },
  {
    _id: "16",
    title: "Social media",
    createdAt: new Date(),
    description: "Social media dashboard with theme switcher",
    image: "assets/img/projects/16.jpg",
    tags: ["Html5", "Css3", "Javascript", "Bem", "Dark Mode", "Light Mode"],
    source:
      "https://github.com/jerson100/social-media-dashboard-with-theme-switcher-master",
    linkApp:
      "https://jerson100.github.io/social-media-dashboard-with-theme-switcher-master/",
  },
];
